# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 04:55
from __future__ import unicode_literals

import apps.premium_product.models
import core.django.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=128, verbose_name='name_en')),
                ('name_cn', models.CharField(blank=True, max_length=128, verbose_name='name_cn')),
                ('pinyin', models.TextField(blank=True, max_length=512, verbose_name='pinyin')),
                ('pic', stdimage.models.StdImageField(blank=True, null=True, upload_to=apps.premium_product.models.get_premium_product_pic_path, verbose_name='picture')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='alias')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.Brand', verbose_name='brand')),
            ],
            options={
                'verbose_name': 'PremiumProduct',
                'verbose_name_plural': 'PremiumProducts',
            },
            bases=(core.django.models.ResizeUploadedImageModelMixin, core.django.models.PinYinFieldModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PremiumProductFit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, choices=[('急镇定', '急镇定'), ('抗轻衰', '抗轻衰'), ('收毛孔', '收毛孔'), ('清痘痘', '清痘痘'), ('祛暗沉', '祛暗沉'), ('调水油', '调水油')], max_length=64, verbose_name='目标')),
                ('skin_type', models.CharField(blank=True, choices=[('干性肌肤', '干性肌肤'), ('油性肌肤', '油性肌肤')], max_length=64, verbose_name='肤质')),
                ('category', models.CharField(blank=True, choices=[('乳液/面霜', '乳液/面霜'), ('卸妆', '卸妆'), ('去角质', '去角质'), ('化妆水', '化妆水'), ('洁面', '洁面'), ('精华', '精华'), ('防晒', '防晒'), ('面膜', '面膜')], max_length=64, verbose_name='分类')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='premium_product.PremiumProduct')),
            ],
        ),
    ]
