# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-27 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumproductfit',
            name='purpose',
            field=models.CharField(blank=True, choices=[('急镇定', '急镇定'), ('抗轻衰', '抗轻衰'), ('收毛孔', '收毛孔'), ('清痘痘', '清痘痘'), ('祛暗沉', '祛暗沉'), ('调水油', '调水油'), ('种草', '种草')], max_length=64, verbose_name='目标'),
        ),
    ]
