# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_product', '0002_auto_20180527_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumproductfit',
            name='category',
            field=models.CharField(blank=True, choices=[('卸妆', '卸妆'), ('洁面', '洁面'), ('化妆水', '化妆水'), ('乳液/面霜', '乳液/面霜'), ('精华', '精华'), ('去角质', '去角质'), ('面膜', '面膜'), ('防晒', '防晒')], max_length=64, verbose_name='分类'),
        ),
    ]
