# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_product', '0003_auto_20180610_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumproduct',
            name='alias',
            field=models.CharField(blank=True, max_length=512, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='premiumproduct',
            name='name_cn',
            field=models.CharField(blank=True, max_length=512, verbose_name='name_cn'),
        ),
        migrations.AlterField(
            model_name='premiumproduct',
            name='name_en',
            field=models.CharField(blank=True, max_length=512, verbose_name='name_en'),
        ),
        migrations.AlterField(
            model_name='premiumproduct',
            name='pinyin',
            field=models.TextField(blank=True, max_length=1024, verbose_name='pinyin'),
        ),
    ]
