# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 04:55
from __future__ import unicode_literals

import apps.product.models
import core.django.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='name_en')),
                ('name_cn', models.CharField(blank=True, max_length=255, verbose_name='name_cn')),
                ('pinyin', models.CharField(blank=True, max_length=255, verbose_name='pinyin')),
                ('pic', stdimage.models.StdImageField(blank=True, null=True, upload_to=apps.product.models.get_product_pic_path, verbose_name='picture')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='alias')),
                ('category', models.CharField(blank=True, choices=[('乳液/面霜', '乳液/面霜'), ('卸妆', '卸妆'), ('去角质', '去角质'), ('化妆水', '化妆水'), ('洁面', '洁面'), ('精华', '精华'), ('防晒', '防晒'), ('面膜', '面膜')], max_length=64)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.Brand')),
            ],
            bases=(core.django.models.ResizeUploadedImageModelMixin, core.django.models.PinYinFieldModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oily_type', models.CharField(blank=True, choices=[('1', '重度油性'), ('2', '轻度油性'), ('3', '轻度干性'), ('4', '重度干性')], max_length=64, verbose_name='油性or干性')),
                ('sensitive_type', models.CharField(blank=True, choices=[('5', '重度敏感性'), ('6', '轻度敏感性'), ('7', '轻度耐受性'), ('8', '耐受性')], max_length=64, verbose_name='敏感or耐受')),
                ('pigment_type', models.CharField(blank=True, choices=[('9', '色素性皮肤'), ('10', '非色素性皮肤')], max_length=64, verbose_name='色素or非色素')),
                ('loose_type', models.CharField(blank=True, choices=[('11', '非紧致性皮肤'), ('12', '紧致性皮肤')], max_length=64, verbose_name='易皱or紧致')),
                ('analysis', models.TextField(blank=True, max_length=64, verbose_name='对应阐述')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('is_safe', models.BooleanField(verbose_name='安全风险')),
                ('is_live', models.BooleanField(verbose_name='活性成分')),
                ('is_pox', models.BooleanField(verbose_name='致痘风险')),
                ('effect', models.CharField(blank=True, max_length=255, verbose_name='使用目的')),
                ('description', models.TextField(blank=True, max_length=512, verbose_name='描述')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
