# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180516_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='productingredient',
            name='safe',
            field=models.CharField(blank=True, max_length=255, verbose_name='safe'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='is_live',
            field=models.BooleanField(default=False, verbose_name='活性成分'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='is_pox',
            field=models.BooleanField(default=False, verbose_name='致痘风险'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='is_safe',
            field=models.BooleanField(default=False, verbose_name='安全风险'),
        ),
    ]
