# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180516_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productingredient',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='product.ProductIngredient', verbose_name='成分组成'),
        ),
    ]
