# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20180529_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productanalysis',
            old_name='loose_type2',
            new_name='loose_type',
        ),
        migrations.RenameField(
            model_name='productanalysis',
            old_name='oily_type2',
            new_name='oily_type',
        ),
        migrations.RenameField(
            model_name='productanalysis',
            old_name='pigment_type2',
            new_name='pigment_type',
        ),
        migrations.RenameField(
            model_name='productanalysis',
            old_name='sensitive_type2',
            new_name='sensitive_type',
        ),
    ]
