# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-07 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_auto_20180602_1647'),
        ('product', '0011_auto_20180606_1749'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productanalysis',
            unique_together=set([('product', 'oily_type', 'sensitive_type', 'pigment_type', 'loose_type')]),
        ),
    ]
