# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20180610_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alias',
            field=models.CharField(blank=True, max_length=512, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_cn',
            field=models.CharField(blank=True, max_length=512, verbose_name='name_cn'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=512, verbose_name='name_en'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pinyin',
            field=models.CharField(blank=True, max_length=1024, verbose_name='pinyin'),
        ),
        migrations.AlterField(
            model_name='productanalysis',
            name='analysis',
            field=models.TextField(blank=True, verbose_name='对应阐述'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='effect',
            field=models.TextField(blank=True, verbose_name='使用目的'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='name'),
        ),
    ]
