# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-15 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('premium_product', '0001_initial'),
        ('survey', '0003_auto_20180515_1226'),
        ('product', '0002_auto_20180512_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, choices=[('急镇定', '急镇定'), ('抗轻衰', '抗轻衰'), ('收毛孔', '收毛孔'), ('清痘痘', '清痘痘'), ('祛暗沉', '祛暗沉'), ('调水油', '调水油')], max_length=64)),
                ('level', models.CharField(blank=True, choices=[('9.9', '9.9'), ('98', '98')], max_length=64)),
                ('oily_type', models.CharField(blank=True, choices=[('重度油性', '重度油性'), ('轻度油性', '轻度油性'), ('轻度干性', '轻度干性'), ('重度干性', '重度干性')], max_length=64)),
                ('sensitive_type', models.CharField(blank=True, choices=[('重度敏感性', '重度敏感性'), ('轻度敏感性', '轻度敏感性'), ('轻度耐受性', '轻度耐受性'), ('耐受性', '耐受性')], max_length=64)),
                ('pigment_type', models.CharField(blank=True, choices=[('色素性皮肤', '色素性皮肤'), ('非色素性皮肤', '非色素性皮肤')], max_length=64)),
                ('loose_type', models.CharField(blank=True, choices=[('非紧致性皮肤', '非紧致性皮肤'), ('紧致性皮肤', '紧致性皮肤')], max_length=64)),
                ('oily_score', models.PositiveIntegerField(blank=True, null=True)),
                ('sensitivity_score', models.PositiveIntegerField(blank=True, null=True)),
                ('pigment_score', models.PositiveIntegerField(blank=True, null=True)),
                ('loose_score', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, max_length=128)),
                ('problem', models.TextField(blank=True, max_length=128)),
                ('avoid_component', models.TextField(blank=True, max_length=128)),
                ('doctor_advice', models.TextField(blank=True, max_length=128)),
                ('day_instruct', models.CharField(blank=True, max_length=512)),
                ('night_instruct', models.CharField(blank=True, max_length=512)),
                ('mask_instruct', models.CharField(blank=True, max_length=512)),
                ('emergency_solution', models.TextField(blank=True, max_length=128)),
                ('maintain_solution', models.TextField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='ReportProductAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('日间', '日间'), ('夜间', '夜间'), ('面膜', '面膜')], max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium_product.PremiumProduct')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportProductAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('analysis', models.TextField(blank=True, max_length=128)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Report')),
            ],
        ),
    ]
