# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20180517_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='level',
            field=models.CharField(blank=True, choices=[('9.9', '9.9'), ('98', '98')], max_length=64, verbose_name='价位'),
        ),
        migrations.AlterField(
            model_name='report',
            name='purpose',
            field=models.CharField(blank=True, choices=[('急镇定', '急镇定'), ('抗轻衰', '抗轻衰'), ('收毛孔', '收毛孔'), ('清痘痘', '清痘痘'), ('祛暗沉', '祛暗沉'), ('调水油', '调水油')], max_length=64, verbose_name='目标'),
        ),
    ]
