# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20180529_0727'),
        ('report', '0005_report_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='loose_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_loose_type', to='analysis.SkinType', verbose_name='易皱纹or紧致'),
        ),
        migrations.AddField(
            model_name='report',
            name='oily_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_oily_type', to='analysis.SkinType', verbose_name='油性or干性'),
        ),
        migrations.AddField(
            model_name='report',
            name='pigment_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_pigment_type', to='analysis.SkinType', verbose_name='色素or非色素'),
        ),
        migrations.AddField(
            model_name='report',
            name='remark',
            field=models.TextField(blank=True, max_length=128, verbose_name='温馨提示'),
        ),
        migrations.AddField(
            model_name='report',
            name='sensitive_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_sensitive_type', to='analysis.SkinType', verbose_name='敏感or耐受'),
        ),
    ]
