# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    SkinType = apps.get_model('analysis', 'SkinType')
    ProductAnalysis = apps.get_model('product', 'ProductAnalysis')
    for w in ProductAnalysis.objects.all():
        if w.oily_type:
            w.oily_type2 = SkinType.objects.get(name=w.oily_type)
        else:
            print('Word #%s failed' % w.id)
        if w.sensitive_type:
            w.sensitive_type2 = SkinType.objects.get(name=w.sensitive_type)
        else:
            print('Word #%s failed' % w.id)
        if w.pigment_type:
            w.pigment_type2 = SkinType.objects.get(name=w.pigment_type)
        else:
            print('Word #%s failed' % w.id)
        if w.loose_type:
            w.loose_type2 = SkinType.objects.get(name=w.loose_type)
        else:
            print('Word #%s failed' % w.id)
        w.save()


def backward(apps, schema_editor):
    # do nothing
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('report', '0006_auto_20180529_0727'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
