# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_product', '0002_auto_20180527_1540'),
        ('report', '0009_auto_20180529_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='day_instruct',
        ),
        migrations.RemoveField(
            model_name='report',
            name='mask_instruct',
        ),
        migrations.RemoveField(
            model_name='report',
            name='night_instruct',
        ),
        migrations.AddField(
            model_name='report',
            name='day_products',
            field=models.ManyToManyField(blank=True, related_name='day_products', to='premium_product.PremiumProduct', verbose_name='日间'),
        ),
        migrations.AddField(
            model_name='report',
            name='mask_products',
            field=models.ManyToManyField(blank=True, related_name='mask_products', to='premium_product.PremiumProduct', verbose_name='面膜'),
        ),
        migrations.AddField(
            model_name='report',
            name='night_products',
            field=models.ManyToManyField(blank=True, related_name='night_products', to='premium_product.PremiumProduct', verbose_name='夜间'),
        ),
    ]
