# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20180529_2136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportProductAdvice',
            new_name='ReportPremiumProduct',
        ),
        migrations.RemoveField(
            model_name='report',
            name='day_products',
        ),
        migrations.RemoveField(
            model_name='report',
            name='mask_products',
        ),
        migrations.RemoveField(
            model_name='report',
            name='night_products',
        ),
    ]
