# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_report_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='allergy',
            field=models.TextField(blank=True, verbose_name='过敏'),
        ),
        migrations.AlterField(
            model_name='report',
            name='avoid_component',
            field=models.TextField(blank=True, verbose_name='4) 需要避免使用的皮肤护理成分'),
        ),
        migrations.AlterField(
            model_name='report',
            name='doctor_advice',
            field=models.TextField(blank=True, verbose_name='三、听听皮肤科医生怎么说'),
        ),
        migrations.AlterField(
            model_name='report',
            name='emergency_solution',
            field=models.TextField(blank=True, verbose_name='应急方案'),
        ),
        migrations.AlterField(
            model_name='report',
            name='maintain_solution',
            field=models.TextField(blank=True, verbose_name='日常维稳方案'),
        ),
        migrations.AlterField(
            model_name='report',
            name='problem',
            field=models.TextField(blank=True, verbose_name='2. 我们认为您存在的问题'),
        ),
        migrations.AlterField(
            model_name='report',
            name='remark',
            field=models.TextField(blank=True, verbose_name='温馨提示'),
        ),
        migrations.AlterField(
            model_name='report',
            name='summary',
            field=models.TextField(blank=True, verbose_name='总结'),
        ),
    ]
