# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_auto_20180611_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='day_instruct',
            field=models.TextField(blank=True, verbose_name='日间'),
        ),
        migrations.AlterField(
            model_name='report',
            name='mask_instruct',
            field=models.TextField(blank=True, verbose_name='面膜'),
        ),
        migrations.AlterField(
            model_name='report',
            name='night_instruct',
            field=models.TextField(blank=True, verbose_name='夜间'),
        ),
        migrations.AlterField(
            model_name='reportproductanalysis',
            name='analysis',
            field=models.TextField(blank=True, verbose_name='分析'),
        ),
        migrations.AlterField(
            model_name='reportproductanalysis',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='名称'),
        ),
    ]
