# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_auto_20180612_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf',
            field=models.FileField(blank=True, upload_to='', verbose_name='PDF'),
        ),
        migrations.AddField(
            model_name='report',
            name='pdf_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PDF生成时间'),
        ),
    ]
