# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-15 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_auto_20180614_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
