# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, choices=[('急镇定', '急镇定'), ('抗轻衰', '抗轻衰'), ('收毛孔', '收毛孔'), ('清痘痘', '清痘痘'), ('祛暗沉', '祛暗沉'), ('调水油', '调水油')], max_length=64)),
                ('oily_type', models.CharField(blank=True, choices=[('1', '重度油性'), ('2', '轻度油性'), ('3', '轻度干性'), ('4', '重度干性')], max_length=64)),
                ('sensitive_type', models.CharField(blank=True, choices=[('5', '重度敏感性'), ('6', '轻度敏感性'), ('7', '轻度耐受性'), ('8', '耐受性')], max_length=64)),
                ('pigment_type', models.CharField(blank=True, choices=[('9', '色素性皮肤'), ('10', '非色素性皮肤')], max_length=64)),
                ('loose_type', models.CharField(blank=True, choices=[('11', '非紧致性皮肤'), ('12', '紧致性皮肤')], max_length=64)),
                ('report', models.TextField(blank=True, max_length=512)),
                ('avoid_component', models.TextField(blank=True, max_length=128)),
                ('doctor_advice', models.TextField(blank=True, max_length=128)),
                ('emergency_solution', models.TextField(blank=True, max_length=128)),
                ('maintain_solution', models.TextField(blank=True, max_length=128)),
                ('day_instruct', models.CharField(blank=True, max_length=512)),
                ('night_instruct', models.CharField(blank=True, max_length=512)),
                ('mask_instruct', models.CharField(blank=True, max_length=512)),
                ('problem', models.TextField(blank=True, max_length=128)),
            ],
        ),
    ]
