# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-15 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20180512_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': '话术', 'verbose_name_plural': '话术'},
        ),
        migrations.AlterField(
            model_name='word',
            name='avoid_component',
            field=models.TextField(blank=True, max_length=128, verbose_name='需要避免使用的皮肤护理成分'),
        ),
        migrations.AlterField(
            model_name='word',
            name='day_instruct',
            field=models.CharField(blank=True, max_length=512, verbose_name='日间'),
        ),
        migrations.AlterField(
            model_name='word',
            name='doctor_advice',
            field=models.TextField(blank=True, max_length=128, verbose_name='听听皮肤科医生怎么说'),
        ),
        migrations.AlterField(
            model_name='word',
            name='emergency_solution',
            field=models.TextField(blank=True, max_length=128, verbose_name='应急方案'),
        ),
        migrations.AlterField(
            model_name='word',
            name='loose_type',
            field=models.CharField(blank=True, choices=[('非紧致性皮肤', '非紧致性皮肤'), ('紧致性皮肤', '紧致性皮肤')], max_length=64, verbose_name='易皱纹or紧致'),
        ),
        migrations.AlterField(
            model_name='word',
            name='maintain_solution',
            field=models.TextField(blank=True, max_length=128, verbose_name='日常维稳方案'),
        ),
        migrations.AlterField(
            model_name='word',
            name='mask_instruct',
            field=models.CharField(blank=True, max_length=512, verbose_name='面膜'),
        ),
        migrations.AlterField(
            model_name='word',
            name='night_instruct',
            field=models.CharField(blank=True, max_length=512, verbose_name='夜间'),
        ),
        migrations.AlterField(
            model_name='word',
            name='oily_type',
            field=models.CharField(blank=True, choices=[('重度油性', '重度油性'), ('轻度油性', '轻度油性'), ('轻度干性', '轻度干性'), ('重度干性', '重度干性')], max_length=64, verbose_name='油性or干性'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pigment_type',
            field=models.CharField(blank=True, choices=[('色素性皮肤', '色素性皮肤'), ('非色素性皮肤', '非色素性皮肤')], max_length=64, verbose_name='色素or非色素'),
        ),
        migrations.AlterField(
            model_name='word',
            name='problem',
            field=models.TextField(blank=True, max_length=128, verbose_name='我们认为您存在的问题'),
        ),
        migrations.AlterField(
            model_name='word',
            name='purpose',
            field=models.CharField(blank=True, choices=[('急镇定', '急镇定'), ('抗轻衰', '抗轻衰'), ('收毛孔', '收毛孔'), ('清痘痘', '清痘痘'), ('祛暗沉', '祛暗沉'), ('调水油', '调水油')], max_length=64, verbose_name='目标'),
        ),
        migrations.AlterField(
            model_name='word',
            name='report',
            field=models.TextField(blank=True, max_length=512, verbose_name='皮肤检测报告总结'),
        ),
        migrations.AlterField(
            model_name='word',
            name='sensitive_type',
            field=models.CharField(blank=True, choices=[('重度敏感性', '重度敏感性'), ('轻度敏感性', '轻度敏感性'), ('轻度耐受性', '轻度耐受性'), ('耐受性', '耐受性')], max_length=64, verbose_name='敏感or耐受'),
        ),
    ]
