# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20180527_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('油性or干性', '油性or干性'), ('敏感or耐受', '敏感or耐受'), ('色素or非色素', '色素or非色素'), ('易皱纹or紧致', '易皱纹or紧致')], max_length=64, verbose_name='维度')),
                ('name', models.CharField(blank=True, choices=[('重度油性', '重度油性'), ('轻度油性', '轻度油性'), ('轻度干性', '轻度干性'), ('重度干性', '重度干性'), ('重度敏感性', '重度敏感性'), ('轻度敏感性', '轻度敏感性'), ('轻度耐受性', '轻度耐受性'), ('耐受性', '耐受性'), ('色素性', '色素性'), ('非色素性', '非色素性'), ('非紧致性', '非紧致性'), ('紧致性', '紧致性')], max_length=64, verbose_name='名称')),
                ('short_name', models.CharField(blank=True, max_length=64, verbose_name='简称')),
                ('description', models.TextField(blank=True, max_length=128, verbose_name='类型')),
            ],
        ),
    ]
