# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_skintype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skintype',
            old_name='type',
            new_name='dimension',
        ),
    ]
