# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20180528_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='loose_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_loose_type', to='analysis.SkinType', verbose_name='易皱纹or紧致'),
        ),
        migrations.AddField(
            model_name='word',
            name='oily_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_oily_type', to='analysis.SkinType', verbose_name='油性or干性'),
        ),
        migrations.AddField(
            model_name='word',
            name='pigment_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_pigment_type', to='analysis.SkinType', verbose_name='色素or非色素'),
        ),
        migrations.AddField(
            model_name='word',
            name='sensitive_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_sensitive_type', to='analysis.SkinType', verbose_name='敏感or耐受'),
        ),
    ]
