# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_auto_20180529_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='avoid_component',
            field=models.TextField(blank=True, max_length=1024, verbose_name='需要避免使用的皮肤护理成分'),
        ),
        migrations.AlterField(
            model_name='word',
            name='doctor_advice',
            field=models.TextField(blank=True, max_length=1024, verbose_name='听听皮肤科医生怎么说'),
        ),
        migrations.AlterField(
            model_name='word',
            name='emergency_solution',
            field=models.TextField(blank=True, max_length=1024, verbose_name='应急方案'),
        ),
        migrations.AlterField(
            model_name='word',
            name='maintain_solution',
            field=models.TextField(blank=True, max_length=1024, verbose_name='日常维稳方案'),
        ),
        migrations.AlterField(
            model_name='word',
            name='problem',
            field=models.TextField(blank=True, max_length=1024, verbose_name='我们认为您存在的问题'),
        ),
    ]
