# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-02 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_auto_20180529_2019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set([('purpose', 'oily_type', 'sensitive_type', 'pigment_type', 'loose_type')]),
        ),
    ]
