# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_auto_20180611_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skintype',
            name='description',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='skintype',
            name='short_description',
            field=models.TextField(blank=True, max_length=512, verbose_name='简评'),
        ),
        migrations.AlterField(
            model_name='word',
            name='avoid_component',
            field=models.TextField(blank=True, verbose_name='需要避免使用的皮肤护理成分'),
        ),
        migrations.AlterField(
            model_name='word',
            name='day_instruct',
            field=models.TextField(blank=True, verbose_name='日间'),
        ),
        migrations.AlterField(
            model_name='word',
            name='doctor_advice',
            field=models.TextField(blank=True, verbose_name='听听皮肤科医生怎么说'),
        ),
        migrations.AlterField(
            model_name='word',
            name='emergency_solution',
            field=models.TextField(blank=True, verbose_name='应急方案'),
        ),
        migrations.AlterField(
            model_name='word',
            name='maintain_solution',
            field=models.TextField(blank=True, verbose_name='日常维稳方案'),
        ),
        migrations.AlterField(
            model_name='word',
            name='mask_instruct',
            field=models.TextField(blank=True, verbose_name='面膜'),
        ),
        migrations.AlterField(
            model_name='word',
            name='night_instruct',
            field=models.TextField(blank=True, verbose_name='夜间'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pinyin',
            field=models.CharField(blank=True, max_length=1024, verbose_name='pinyin'),
        ),
        migrations.AlterField(
            model_name='word',
            name='problem',
            field=models.TextField(blank=True, verbose_name='我们认为您存在的问题'),
        ),
        migrations.AlterField(
            model_name='word',
            name='report',
            field=models.TextField(blank=True, verbose_name='皮肤检测报告总结'),
        ),
    ]
