# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_auto_20180612_1454'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skintype',
            unique_together=set([('dimension', 'name')]),
        ),
    ]
