# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuser',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新'),
        ),
    ]
