# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 04:55
from __future__ import unicode_literals

import core.django.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('pinyin', models.CharField(blank=True, max_length=512, verbose_name='pinyin')),
                ('sex', models.CharField(choices=[('女', '女'), ('男', '男')], max_length=30, verbose_name='性别')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='手机')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='身高')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='体重')),
                ('job', models.CharField(blank=True, max_length=64, verbose_name='职业')),
                ('monthly_income', models.CharField(blank=True, choices=[('0-5000', '0-5000'), ('5001-10000', '5001-10000'), ('10001-20000', '10001-20000'), ('20000+', '20000+'), ('全职太太/先生', '全职太太/先生')], max_length=50, verbose_name='收入')),
                ('weixin_id', models.CharField(blank=True, max_length=128, verbose_name='微信号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('wx_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.WxUser')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customer',
            },
            bases=(core.django.models.PinYinFieldModelMixin, models.Model),
        ),
    ]
