# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180520_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=512, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='job',
            field=models.CharField(blank=True, max_length=255, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pinyin',
            field=models.CharField(blank=True, max_length=1024, verbose_name='pinyin'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='remark',
            field=models.CharField(blank=True, max_length=512, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weixin_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='微信号'),
        ),
    ]
