# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180612_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='monthly_income',
            field=models.CharField(blank=True, choices=[('0-5000', 'A. 0-5000'), ('5001-10000', 'B. 5001-10000'), ('10001-20000', 'C. 10001-20000'), ('20000+', 'D. 20000+'), ('全职太太', 'E. 全职太太/先生')], max_length=50, verbose_name='收入'),
        ),
    ]
