# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('premium_product', '0001_initial'),
        ('customer', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, choices=[('急镇定', '急镇定'), ('抗轻衰', '抗轻衰'), ('收毛孔', '收毛孔'), ('清痘痘', '清痘痘'), ('祛暗沉', '祛暗沉'), ('调水油', '调水油')], max_length=64)),
                ('level', models.CharField(blank=True, choices=[('9.9', '9.9'), ('98', '98')], max_length=64)),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('女', '女'), ('男', '男')], max_length=30, verbose_name='性别')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='手机')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='身高')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='体重')),
                ('job', models.CharField(blank=True, max_length=64, verbose_name='职业')),
                ('monthly_income', models.CharField(blank=True, choices=[('0-5000', '0-5000'), ('5001-10000', '5001-10000'), ('10001-20000', '10001-20000'), ('20000+', '20000+'), ('全职太太/先生', '全职太太/先生')], max_length=50, verbose_name='收入')),
                ('weixin_id', models.CharField(blank=True, max_length=128, verbose_name='微信号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('question1', models.PositiveIntegerField(blank=True, null=True)),
                ('question2', models.PositiveIntegerField(blank=True, null=True)),
                ('question3', models.PositiveIntegerField(blank=True, null=True)),
                ('question4', models.PositiveIntegerField(blank=True, null=True)),
                ('question5', models.PositiveIntegerField(blank=True, null=True)),
                ('question6', models.PositiveIntegerField(blank=True, null=True)),
                ('question7', models.PositiveIntegerField(blank=True, null=True)),
                ('question8', models.PositiveIntegerField(blank=True, null=True)),
                ('question9', models.PositiveIntegerField(blank=True, null=True)),
                ('question10', models.PositiveIntegerField(blank=True, null=True)),
                ('question11', models.PositiveIntegerField(blank=True, null=True)),
                ('question12', models.PositiveIntegerField(blank=True, null=True)),
                ('question13', models.PositiveIntegerField(blank=True, null=True)),
                ('question14', models.PositiveIntegerField(blank=True, null=True)),
                ('question15', models.PositiveIntegerField(blank=True, null=True)),
                ('question16', models.PositiveIntegerField(blank=True, null=True)),
                ('question17', models.PositiveIntegerField(blank=True, null=True)),
                ('question18', models.PositiveIntegerField(blank=True, null=True)),
                ('question19', models.PositiveIntegerField(blank=True, null=True)),
                ('question20', models.PositiveIntegerField(blank=True, null=True)),
                ('question21', models.PositiveIntegerField(blank=True, null=True)),
                ('question22', models.PositiveIntegerField(blank=True, null=True)),
                ('question23', models.PositiveIntegerField(blank=True, null=True)),
                ('question24', models.PositiveIntegerField(blank=True, null=True)),
                ('question25', models.PositiveIntegerField(blank=True, null=True)),
                ('question26', models.PositiveIntegerField(blank=True, null=True)),
                ('question27', models.PositiveIntegerField(blank=True, null=True)),
                ('question28', models.PositiveIntegerField(blank=True, null=True)),
                ('question29', models.PositiveIntegerField(blank=True, null=True)),
                ('question30', models.PositiveIntegerField(blank=True, null=True)),
                ('question31', models.PositiveIntegerField(blank=True, null=True)),
                ('question32', models.PositiveIntegerField(blank=True, null=True)),
                ('question33', models.PositiveIntegerField(blank=True, null=True)),
                ('question34', models.PositiveIntegerField(blank=True, null=True)),
                ('question35', models.PositiveIntegerField(blank=True, null=True)),
                ('question36', models.PositiveIntegerField(blank=True, null=True)),
                ('question37', models.PositiveIntegerField(blank=True, null=True)),
                ('question38', models.PositiveIntegerField(blank=True, null=True)),
                ('allergy', models.TextField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, choices=[('急镇定', '急镇定'), ('抗轻衰', '抗轻衰'), ('收毛孔', '收毛孔'), ('清痘痘', '清痘痘'), ('祛暗沉', '祛暗沉'), ('调水油', '调水油')], max_length=64)),
                ('level', models.CharField(blank=True, choices=[('9.9', '9.9'), ('98', '98')], max_length=64)),
                ('oily_type', models.CharField(blank=True, choices=[('1', '重度油性'), ('2', '轻度油性'), ('3', '轻度干性'), ('4', '重度干性')], max_length=64)),
                ('sensitive_type', models.CharField(blank=True, choices=[('5', '重度敏感性'), ('6', '轻度敏感性'), ('7', '轻度耐受性'), ('8', '耐受性')], max_length=64)),
                ('pigment_type', models.CharField(blank=True, choices=[('9', '色素性皮肤'), ('10', '非色素性皮肤')], max_length=64)),
                ('loose_type', models.CharField(blank=True, choices=[('11', '非紧致性皮肤'), ('12', '紧致性皮肤')], max_length=64)),
                ('oily_score', models.PositiveIntegerField(blank=True, null=True)),
                ('sensitivity_score', models.PositiveIntegerField(blank=True, null=True)),
                ('pigment_score', models.PositiveIntegerField(blank=True, null=True)),
                ('loose_score', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, max_length=128)),
                ('problem', models.TextField(blank=True, max_length=128)),
                ('avoid_component', models.TextField(blank=True, max_length=128)),
                ('doctor_advice', models.TextField(blank=True, max_length=128)),
                ('day_instruct', models.CharField(blank=True, max_length=512)),
                ('night_instruct', models.CharField(blank=True, max_length=512)),
                ('mask_instruct', models.CharField(blank=True, max_length=512)),
                ('emergency_solution', models.TextField(blank=True, max_length=128)),
                ('maintain_solution', models.TextField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='ReportProductAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('日间', '日间'), ('夜间', '夜间'), ('面膜', '面膜')], max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium_product.PremiumProduct')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportProductAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('analysis', models.TextField(blank=True, max_length=128)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Report')),
            ],
        ),
    ]
