# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 11:05
from __future__ import unicode_literals

import apps.survey.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20180515_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='fill_blank_question1',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='fill_blank_question10',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='fill_blank_question2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='fill_blank_question3',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='fill_blank_question4',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='fill_blank_question5',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='fill_blank_question6',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='fill_blank_question7',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='fill_blank_question8',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='fill_blank_question9',
        ),
        migrations.AddField(
            model_name='answer',
            name='cosmetic_question1',
            field=models.TextField(blank=True, max_length=255, verbose_name='65. 目前正在使用的卸妆类的护肤品名)：'),
        ),
        migrations.AddField(
            model_name='answer',
            name='cosmetic_question2',
            field=models.TextField(blank=True, max_length=255, verbose_name='66、目前正在使用的洁面乳/洁面霜/洁面油类的护肤品名称'),
        ),
        migrations.AddField(
            model_name='answer',
            name='cosmetic_question3',
            field=models.TextField(blank=True, max_length=255, verbose_name='67、目前正在所使用化妆水类护肤品名称'),
        ),
        migrations.AddField(
            model_name='answer',
            name='cosmetic_question4',
            field=models.TextField(blank=True, max_length=255, verbose_name='68、目前正在所使用乳液／面霜类护肤品名称'),
        ),
        migrations.AddField(
            model_name='answer',
            name='cosmetic_question5',
            field=models.TextField(blank=True, max_length=255, verbose_name='69、目前正在使用的精华类的护肤品名称'),
        ),
        migrations.AddField(
            model_name='answer',
            name='cosmetic_question6',
            field=models.TextField(blank=True, max_length=255, verbose_name='70、目前正在使用的去角质类的护肤品名称'),
        ),
        migrations.AddField(
            model_name='answer',
            name='cosmetic_question7',
            field=models.TextField(blank=True, max_length=255, verbose_name='71、目前正在使用的的面膜类的护肤品名称'),
        ),
        migrations.AddField(
            model_name='answer',
            name='cosmetic_question8',
            field=models.TextField(blank=True, max_length=255, verbose_name='72、目前正在使用的防晒类的护肤品名称'),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_changeable',
            field=models.BooleanField(default=True, verbose_name='是否可修改'),
        ),
        migrations.AddField(
            model_name='answer',
            name='other_question1',
            field=models.TextField(blank=True, max_length=255, verbose_name='73、您是否每天（一年四季，不管晴天、阴天、雨天，室内室外）涂抹足量（面部一元硬币大小）专门的防晒产品（不包括隔离霜，底妆）？'),
        ),
        migrations.AddField(
            model_name='answer',
            name='other_question2',
            field=models.TextField(blank=True, help_text='提示：如没有，请填写无', max_length=255, verbose_name='74、您使用哪些成分或护肤品会过敏？如果有请描述过敏的现象。'),
        ),
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('CREATED', '新建'), ('FILLED', '回答完毕'), ('FINISHED', '完成')], default='CREATED', max_length=32, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='answer',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='birth',
            field=models.DateTimeField(blank=True, help_text='提示：格式：2017-01-01', null=True, verbose_name='6. 您的出生日期？'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='cosmetics',
            field=stdimage.models.StdImageField(blank=True, help_text='提示：上传文件不超过4M', null=True, upload_to=apps.survey.models.get_answer_photo_path, verbose_name='5. 现阶段使用护肤品合集'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='monthly_income',
            field=models.CharField(blank=True, choices=[('0-5000', 'A. 0-5000'), ('5001-10000', 'B. 5001-10000'), ('10001-20000', 'C. 10001-20000'), ('20000+', 'D. 20000+'), ('全职太太/先生', 'E. 全职太太/先生')], max_length=50, verbose_name='9. 月收入水平？'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(blank=True, help_text='提示：请填写您下单时登记的姓名', max_length=64, null=True, verbose_name='1. 您的姓名？'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='non_score_question15',
            field=models.CharField(blank=True, max_length=255, verbose_name='64. 近半年内您是否有出现过严重的皮肤问题(例如：大面积的痤疮. 湿疹. 皮肤过敏),请详细描述具体情况：'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='portrait',
            field=stdimage.models.StdImageField(blank=True, help_text='提示：上传文件不超过4M', null=True, upload_to=apps.survey.models.get_answer_photo_path, verbose_name='3. 无PS、无滤镜、清晰纯素颜照片一张'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='portrait_part',
            field=stdimage.models.StdImageField(blank=True, help_text='提示：上传文件不超过4M', null=True, upload_to=apps.survey.models.get_answer_photo_path, verbose_name='4. 如需重点关注部位可在此上传无PS、无滤镜、清晰的纯素颜照片'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question11',
            field=models.PositiveIntegerField(blank=True, help_text='提示：不是痘印', null=True, verbose_name='22. 你的面部会出现泛红的情况（点状或片状）吗？'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question21',
            field=models.PositiveIntegerField(blank=True, help_text='提示：成片的红血丝或根根分明的红血丝', null=True, verbose_name='32. 你脸上哪些部位有红血丝？'),
        ),
    ]
