# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20180517_0715'),
        ('survey', '0004_auto_20180520_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='邀请码')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='姓名')),
                ('is_used', models.BooleanField(default=False, verbose_name='已使用')),
                ('expiry_at', models.DateTimeField(verbose_name='创建时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UsingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='product name')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='remark',
            field=models.TextField(default='', max_length=255, verbose_name='备注'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='birth',
            field=models.DateField(blank=True, help_text='提示：格式：2017-01-01', null=True, verbose_name='6. 您的出生日期？'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='non_score_question15',
            field=models.TextField(blank=True, help_text='提示：如没有，请留空', max_length=255, verbose_name='64. 近半年内您是否有出现过严重的皮肤问题(例如：大面积的痤疮. 湿疹. 皮肤过敏),请详细描述具体情况：'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='other_question2',
            field=models.TextField(blank=True, help_text='提示：如没有，请留空', max_length=255, verbose_name='74、您使用哪些成分或护肤品会过敏？如果有请描述过敏的现象。'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='uuid'),
        ),
        migrations.AddField(
            model_name='answer',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.InviteCode'),
        ),
    ]
