# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20180517_0715'),
        ('survey', '0005_auto_20180522_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='product name')),
                ('analysis', models.TextField(max_length=255, verbose_name='product analysis')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='answer',
            name='cosmetic_question1',
            field=models.TextField(blank=True, max_length=255, verbose_name='65. 目前正在使用的卸妆类的护肤品名'),
        ),
        migrations.AddField(
            model_name='answer',
            name='cosmetic_products1',
            field=models.ManyToManyField(blank=True, related_name='cosmetic_products1', to='survey.AnswerProduct', verbose_name='65. 目前正在使用的卸妆类的护肤品名'),
        ),
        migrations.AddField(
            model_name='answer',
            name='cosmetic_products2',
            field=models.ManyToManyField(blank=True, related_name='cosmetic_products2', to='survey.AnswerProduct', verbose_name='66、目前正在使用的洁面乳/洁面霜/洁面油类的护肤品名称'),
        ),
        migrations.AddField(
            model_name='answer',
            name='cosmetic_products3',
            field=models.ManyToManyField(blank=True, related_name='cosmetic_products3', to='survey.AnswerProduct', verbose_name='67、目前正在所使用化妆水类护肤品名称'),
        ),
        migrations.AddField(
            model_name='answer',
            name='cosmetic_products4',
            field=models.ManyToManyField(blank=True, related_name='cosmetic_products4', to='survey.AnswerProduct', verbose_name='68、目前正在所使用乳液／面霜类护肤品名称'),
        ),
        migrations.AddField(
            model_name='answer',
            name='cosmetic_products5',
            field=models.ManyToManyField(blank=True, related_name='cosmetic_products5', to='survey.AnswerProduct', verbose_name='69、目前正在使用的精华类的护肤品名称'),
        ),
        migrations.AddField(
            model_name='answer',
            name='cosmetic_products6',
            field=models.ManyToManyField(blank=True, related_name='cosmetic_products6', to='survey.AnswerProduct', verbose_name='70、目前正在使用的去角质类的护肤品名称'),
        ),
        migrations.AddField(
            model_name='answer',
            name='cosmetic_products7',
            field=models.ManyToManyField(blank=True, related_name='cosmetic_products7', to='survey.AnswerProduct', verbose_name='71、目前正在使用的的面膜类的护肤品名称'),
        ),
        migrations.AddField(
            model_name='answer',
            name='cosmetic_products8',
            field=models.ManyToManyField(blank=True, related_name='cosmetic_products8', to='survey.AnswerProduct', verbose_name='72、目前正在使用的防晒类的护肤品名称'),
        ),
    ]
