# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20180522_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='cosmetic_question1',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='cosmetic_question2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='cosmetic_question3',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='cosmetic_question4',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='cosmetic_question5',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='cosmetic_question6',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='cosmetic_question7',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='cosmetic_question8',
        ),
    ]
