# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20180522_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.InviteCode'),
        ),
    ]
