# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20180524_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='level',
            field=models.CharField(blank=True, choices=[('9.9', '9.9'), ('98', '98')], max_length=64, verbose_name='价位'),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='purpose',
            field=models.CharField(blank=True, choices=[('急镇定', '急镇定'), ('抗轻衰', '抗轻衰'), ('收毛孔', '收毛孔'), ('清痘痘', '清痘痘'), ('祛暗沉', '祛暗沉'), ('调水油', '调水油')], max_length=64, verbose_name='目标'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='cosmetic_products1',
            field=models.ManyToManyField(blank=True, related_name='cosmetic_products1', to='survey.AnswerProduct', verbose_name='65. 目前正在使用的卸妆类的护肤品名'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='cosmetic_products2',
            field=models.ManyToManyField(blank=True, related_name='cosmetic_products2', to='survey.AnswerProduct', verbose_name='66、目前正在使用的洁面乳/洁面霜/洁面油类的护肤品名称'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='cosmetic_products3',
            field=models.ManyToManyField(blank=True, related_name='cosmetic_products3', to='survey.AnswerProduct', verbose_name='67、目前正在所使用化妆水类护肤品名称'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='cosmetic_products4',
            field=models.ManyToManyField(blank=True, related_name='cosmetic_products4', to='survey.AnswerProduct', verbose_name='68、目前正在所使用乳液／面霜类护肤品名称'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='cosmetic_products5',
            field=models.ManyToManyField(blank=True, related_name='cosmetic_products5', to='survey.AnswerProduct', verbose_name='69、目前正在使用的精华类的护肤品名称'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='cosmetic_products6',
            field=models.ManyToManyField(blank=True, related_name='cosmetic_products6', to='survey.AnswerProduct', verbose_name='70、目前正在使用的去角质类的护肤品名称'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='cosmetic_products7',
            field=models.ManyToManyField(blank=True, related_name='cosmetic_products7', to='survey.AnswerProduct', verbose_name='71、目前正在使用的的面膜类的护肤品名称'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='cosmetic_products8',
            field=models.ManyToManyField(blank=True, related_name='cosmetic_products8', to='survey.AnswerProduct', verbose_name='72、目前正在使用的防晒类的护肤品名称'),
        ),
    ]
