# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20180527_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
    ]
