# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_invitecode_qrcode_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='non_score_question10',
            field=models.CharField(blank=True, max_length=255, verbose_name='59. 夜间-精华'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='non_score_question11',
            field=models.CharField(blank=True, max_length=255, verbose_name='60. 夜间-乳液或面霜'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='non_score_question2',
            field=models.CharField(blank=True, max_length=255, verbose_name='51. 日间-洁面'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='non_score_question3',
            field=models.CharField(blank=True, max_length=255, verbose_name='52. 日间-化妆水'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='non_score_question4',
            field=models.CharField(blank=True, max_length=255, verbose_name='53. 日间-精华'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='non_score_question5',
            field=models.CharField(blank=True, max_length=255, verbose_name='54. 日间-乳液或面霜'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='non_score_question6',
            field=models.CharField(blank=True, max_length=255, verbose_name='55. 日间-防晒'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='non_score_question7',
            field=models.CharField(blank=True, max_length=255, verbose_name='56. 夜间-卸妆'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='non_score_question8',
            field=models.CharField(blank=True, max_length=255, verbose_name='57. 夜间-洁面'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='non_score_question9',
            field=models.CharField(blank=True, max_length=255, verbose_name='58. 夜间-化妆水'),
        ),
    ]
