# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-30 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20180529_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='uuid',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='uuid'),
        ),
    ]
