# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-31 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20180530_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新'),
        ),
    ]
