# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_auto_20180608_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='cosmetic_products1',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='cosmetic_products2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='cosmetic_products3',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='cosmetic_products4',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='cosmetic_products5',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='cosmetic_products6',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='cosmetic_products7',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='cosmetic_products8',
        ),
    ]
