# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_answerproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='job',
            field=models.CharField(blank=True, max_length=255, verbose_name='8. 您目前从事的职业?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='mobile',
            field=models.CharField(blank=True, max_length=32, verbose_name='11. 您的手机号？'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(blank=True, help_text='提示：请填写您下单时登记的姓名', max_length=255, null=True, verbose_name='1. 您的姓名？'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='weixin_id',
            field=models.CharField(blank=True, help_text='提示：微信号不是昵称', max_length=255, verbose_name='10. 您的微信号？'),
        ),
        migrations.AlterField(
            model_name='answerproduct',
            name='analysis',
            field=models.TextField(blank=True, verbose_name='product analysis'),
        ),
        migrations.AlterField(
            model_name='answerproduct',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='qrcode_url',
            field=models.CharField(blank=True, max_length=1024, verbose_name='二维码'),
        ),
    ]
