# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_auto_20180612_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerproduct',
            name='type',
        ),
    ]
