# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-17 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_remove_answerproduct_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='birth',
            field=models.DateField(blank=True, help_text='提示：格式：2017-01-01', null=True, verbose_name='6. 您的出生日期'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='cosmetics',
            field=stdimage.models.StdImageField(blank=True, help_text='提示：上传文件不超过4M', null=True, upload_to=stdimage.utils.UploadToClassNameDir(), verbose_name='5. 现阶段使用护肤品合集'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='7. 您的身高'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='job',
            field=models.CharField(blank=True, max_length=255, verbose_name='8. 您目前从事的职业'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='mobile',
            field=models.CharField(blank=True, max_length=32, verbose_name='11. 您的手机号'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='monthly_income',
            field=models.CharField(blank=True, choices=[('0-5000', 'A. 0-5000'), ('5001-10000', 'B. 5001-10000'), ('10001-20000', 'C. 10001-20000'), ('20000+', 'D. 20000+'), ('全职太太/先生', 'E. 全职太太/先生')], max_length=50, verbose_name='9. 月收入水平'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(blank=True, help_text='提示：请填写您下单时登记的姓名', max_length=255, null=True, verbose_name='1. 您的姓名'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='portrait',
            field=stdimage.models.StdImageField(blank=True, help_text='提示：上传文件不超过4M', null=True, upload_to=stdimage.utils.UploadToClassNameDir(), verbose_name='3. 无PS、无滤镜、清晰纯素颜照片一张'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='portrait_part',
            field=stdimage.models.StdImageField(blank=True, help_text='提示：上传文件不超过4M', null=True, upload_to=stdimage.utils.UploadToClassNameDir(), verbose_name='4. 如需重点关注部位可在此上传无PS、无滤镜、清晰的纯素颜照片'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='sex',
            field=models.CharField(blank=True, choices=[('女', '女'), ('男', '男')], max_length=30, null=True, verbose_name='2. 您的性别'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='体重'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='weixin_id',
            field=models.CharField(blank=True, help_text='提示：微信号不是昵称', max_length=255, verbose_name='10. 您的微信号'),
        ),
    ]
