# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_auto_20180619_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='weixin.WxUser'),
        ),
    ]
