# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name_en',
            field=models.CharField(blank=True, help_text='sdfsdf', max_length=128, verbose_name='name_en'),
        ),
    ]
