# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_auto_20180514_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='name_en'),
        ),
    ]
