# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_auto_20180516_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='alias',
            field=models.CharField(blank=True, max_length=255, verbose_name='别名'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='first_letter_cn',
            field=models.CharField(blank=True, max_length=128, verbose_name='拼音首字母'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='first_letter_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='英文首字母'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name_cn',
            field=models.CharField(blank=True, max_length=128, verbose_name='中文名称'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='英文名称'),
        ),
    ]
